remote_theme: edsandorf/pro-theme

show_navigation: true
show_search_bar: true
show_downloads: true
to_the_top: true

creator: Erlend Dancke Sandorf

e_mail: e.d.sandorf@stir.ac.uk
github_handle: edsandorf
linkedin_handle: erlend-dancke-sandorf
twitter_handle: EDSandorf
